spring:
  datasource:
    url: jdbc:mysql://localhost:3306/${DB_NAME}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:1111}
  security:
    oauth2:
      client:
        registration:
          instagram:
            client-id: ${INSTAGRAM_CLIENT_ID:916068230372786}
            client-secret: ${INSTAGRAM_CLIENT_SECRET:22826d7371a23aec90c3dc9601fcc49b}
            scope:
              - user_profile
            redirect-uri: ${BASE_URI}/login/oauth/code/instagram
            authorization-grant-type: authorization_code
            provider: instagram
        provider:
          instagram:
            authorization-uri: https://api.instagram.com/oauth/authorize
            token-uri: https://api.instagram.com/oauth/access_token
            user-info-uri: https://graph.instagram.com/v20.0/me?fields=id,username&access-token=
            user-name-attribute: username


jwt:
  prefix: ${JWT_PREFIX:Bearer}
  header: ${JWT_HEADER:Authorization}
  secret: ${JWT_SECRET:whsrudgksmsrnralsdufjqnsfjenczndbrbucairk}
  expiration: ${JWT_EXPIRATION:86400000}